### ISSUE TITLE
Error in asMethod(object) 

### ISSUE THREAD

**Issue by AMA111** [ChristophH/sctransform#1] opened 2019-03-15 02:47 UTC
Dear Christoph, 
I am trying sctransform for a large dataset ~150,000 cells but I received this error:

Error in asMethod(object) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105
Calls: source ... apply -> as.matrix -> as.matrix.Matrix -> as -> asMethod
Execution halted

Best,
Abdelrahman

**Comment by ChristophH** [comment] 2019-03-15 10:29
Hi Abdelrahman,
thanks for pointing this out. The error occurs when a large sparse matrix is internally being converted to a dense matrix. This is a bug due to our inefficient way to get the row-wise (per gene) geometric means. I'm working on a fix.

**Comment by AMA111** [comment] 2019-03-15 12:26
Ok. Thank you for that

**Comment by ChristophH** [comment] 2019-03-15 13:22
Fixed as of commit 064d799
Note that for a matrix of this size it will take a few minutes to calculate all cell attributes. Total processing time (including getting cell attributes, doing regression, transforming the data) would be roughly 30 minutes using 1 CPU core, or 20 minutes using 8 cores.

**Closed** 2019-03-16 13:42 UTC

**Comment by AMA111** [comment] 2019-03-28 15:07
Hey Christoph, 
I am running it for almost one week (32 cores - 200 GB ram) and crash then? 
Do you recommend some steps or edits to handle it?
Best,
Abdelrahman

**Comment by ChristophH** [comment] 2019-03-28 15:25
This might be specific to your data, as I have been successfully running it on 150K cells in 30 minutes.
At what step does it crash? What is the output of `traceback()`? What is the exact code that you are running?
