### ISSUE TITLE
return_gene_attr = TRUE parameter causes error

### ISSUE THREAD

**Issue by alorchhota** [ChristophH/sctransform#24] opened 2019-05-15 19:34 UTC
Hi Chris,

Thanks for the nice normalization method. I'm trying to normalize my data (in a `SingleCellExperiment` object) using `vst().` I get an error when I run `vst` with the parameter `return_gene_attr = TRUE`. I don't get any error if I run it with `return_gene_attr = FALSE`. Here is the code and error message.

```
> vst_latent_var = c('log10_total_counts')
> vst_batch_var = NULL
> vst_latent_var_nonreg = NULL
> vst_n_genes = 2000 
> vst_n_cells = 10000
> vst_out <- sctransform::vst(umi = SingleCellExperiment::counts(sce), 
+                             cell_attr = colData(sce), 
+                             latent_var = vst_latent_var, 
+                             batch_var = vst_batch_var,
+                             latent_var_nonreg = vst_latent_var_nonreg,
+                             n_genes = vst_n_genes,
+                             n_cells = vst_n_cells,
+                             return_gene_attr = TRUE, 
+                             return_cell_attr = TRUE, 
+                             method = "poisson", 
+                             do_regularize = TRUE,
+                             residual_type = "pearson",
+                             show_progress = TRUE)
Calculating cell attributes for input UMI matrix
Variance stabilizing transformation of count matrix of size 16733 by 57891
Model formula is y ~ log10_total_counts
Get Negative Binomial regression parameters per gene
Using 2000 genes, 10000 cells
  |======================================================================| 100%
Found 4 outliers - those will be ignored in fitting/regularization step

Second step: Get residuals using fitted parameters for 16733 genes
  |======================================================================| 100%
Calculating gene attributes
Error in row_var_dense(x) : Wrong R type for mapped matrix
In addition: There were 50 or more warnings (use warnings() to see the first 50)

```

Do you have any idea why I get the error and how I can avoid it? Any suggestion is appreciated.

Best,
Ashis

**Comment by ChristophH** [comment] 2019-05-15 20:55
Hi Ashis,
I have not seen this error before. If you can provide a minimal example of the input data that produces the error, I'll have a look.
Do you get expected results when you call `vst` with `return_gene_attr = FALSE`?

**Comment by alorchhota** [comment] 2019-05-15 22:09
Unfortunately, I cannot share the full data. But I'll try to make a minimal example with personal info removed and get back to you.
With `return_gene_attr = F`, I get normalized counts, but I can't make some of the plots.

**Comment by ChristophH** [comment] 2019-05-16 08:34
Note that the count matrix `umi` passed to `vst` should be of class `matrix` or `dgCMatrix`, and not contain NAs, otherwise `sctransform:::row_var` will fail which is what is happening here (same is true for the resulting residual matrix)

**Comment by wmacnair** [comment] 2019-06-05 11:58
Hi, I got the same error message (using a umi of class `matrix`, with no NAs). A quick workaround which worked for me was to convert the counts to a `dgCMatrix` object, e.g. 
```
umi = as(SingleCellExperiment::counts(sce), "dgCMatrix")
```

**Comment by ChristophH** [comment] 2019-08-07 20:31
I have not been able to reproduce this issue with a umi matrix of class `matrix`. If you can provide input that triggers this error, feel free to re-open this issue.

**Comment by asistradition** [comment] 2019-08-15 21:25
```
failure.poc.data <- matrix(c(sample(1:10, 5000, replace=TRUE), sample(1:10, 5000, replace=TRUE), 
                           sample(1:10, 5000, replace=TRUE), sample(1:10, 5000, replace=TRUE)),
                           nrow = 5000, ncol = 4)
rownames(failure.poc.data) <- vapply(1:5000, function(x) {paste0(sample(c("a", "b", "c", "d", "e", "f", "g", "h", "1", "2", "3", "4"), 10, replace=TRUE), collapse = '')}, "")
colnames(failure.poc.data) <- c("GENE1", "GENE2", "GENE3", "GENE4")

vst.obj <- sctransform::vst(t(failure.poc.data), 
                            cell_attr = failure.metadata, 
                            batch_var = "BATCH",
                            n_genes = NULL)
```

> Calculating cell attributes for input UMI matrix
Variance stabilizing transformation of count matrix of size 4 by 5000
Model formula is y ~ (log_umi) : BATCH + BATCH + 0
Get Negative Binomial regression parameters per gene
Using 4 genes, 5000 cells
  |===================================================================================================================| 100%
Second step: Get residuals using fitted parameters for 4 genes
  |===================================================================================================================| 100%
Calculating gene attributes
Error in row_var_dense(x) : Wrong R type for mapped matrix

**Comment by ajabadi** [comment] 2019-09-15 23:31
same issue here as well. Error stack attached below:

```
Error in row_var_dense(x) : Wrong R type for mapped matrix
5.stop(structure(list(message = "Wrong R type for mapped matrix", call = row_var_dense(x), cppstack = NULL), class = c("std::invalid_argument", "C++Error", "error", "condition")))
4.row_var_dense(x)
3.row_var(umi)
2.data.frame(detection_rate = genes_cell_count[genes]/ncol(umi), gmean = 10^genes_log_gmean, variance = row_var(umi))
1.vst(as.matrix(counts(sce2_qc)), n_genes = NULL)

```

**Comment by ajabadi** [comment] 2019-09-15 23:38
Hi, here is a reproducible example creating the mentioned error:
```
library(SingleCellExperiment)
library(sctransform)
library(future)

## load data
data_url <- 'https://github.com/LuyiTian/CellBench_data/blob/master/data/sincell_with_class.RData?raw=true'
load(url(data_url))


## function to filter by mean counts and detection limit
sce_filt <- function(sce, mean_count=0, cell_det=0) {
  stopifnot(cell_det<=1 & cell_det>=0)
  cell_dropout <- (1-cell_det)*100
  sce_rd <- rowData(sce)
  pass_filt <- sce_rd$mean_counts>=mean_count & sce_rd$pct_dropout_by_counts<=cell_dropout
  sce[pass_filt,]
}

## filter out a little
sce2_qc <- sce_filt(sce2_qc, mean_count = 10, cell_det = 0.05)

## VST
set.seed(42)
plan(strategy = "multicore", workers = 3)
vst_sce2 <- vst(as.matrix(counts(sce2_qc)), n_genes = NULL)

#> Calculating cell attributes for input UMI matrix
#> Variance stabilizing transformation of count matrix of size 544 by 340
#> Model formula is y ~ log_umi
#> Get Negative Binomial regression parameters per gene
#> Using 544 genes, 340 cells
#> |===================================================================| 100%
#> Second step: Get residuals using fitted parameters for 544 genes
#> |===================================================================| 100%
#> Calculating gene attributes
#> Error in row_var_dense(x) : Wrong R type for mapped matrix
#> In addition: There were 50 or more warnings (use warnings() to see the first 50)
```

**Comment by ChristophH** [comment] 2019-09-16 12:19
Thank you for providing more detail regarding this issue. But unfortunately I still cannot reproduce the example. Your code fails with the following error message
```
> sce2_qc <- sce_filt(sce2_qc, mean_count = 10, cell_det = 0.05)
Error in rowData(sce) : object 'sce2_qc' not found
```

If I use the `sce_sc_10x_qc` object as input instead I get another error
```
> sce2_qc <- sce_filt(sce_sc_10x_qc, mean_count = 10, cell_det = 0.05)
Error in rowData(sce) : 
  could not find symbol "use.names" in environment of the generic function
```

Could you provide the actual count matrix that is passed to `vst`? Also, does the following change make a difference when calling `vst`: `vst_sce2 <- vst(as(counts(sce2_qc), 'dgCMatrix'), n_genes = NULL)`?

**Comment by asistradition** [comment] 2019-09-16 14:00
> Thank you for providing more detail regarding this issue. But unfortunately I still cannot reproduce the example. Your code fails with the following error message

Does the code I provided two comments up not replicate the problem for you?

**Comment by ChristophH** [comment] 2019-09-16 14:54
@asistradition Yes, your example fails for me and it's due to the storage mode of the count matrix.
If I change the matrix to sparse format or change the values to numeric (from integer) things work:
```
tmp <- sctransform:::row_var(as(failure.poc.data, 'dgCMatrix'))
storage.mode(failure.poc.data) <- 'numeric'
tmp <- sctransform:::row_var(failure.poc.data)
```
I'll see how I can fix this.

**Comment by ChristophH** [comment] 2019-09-16 15:35
The problem was in my C++ wrapper to speed up calculation of row variances for dense matrices. Fixed in develop branch.

**Closed by ChristophH** 2019-09-16 15:35 UTC
